"""billing_upgrade

Revision ID: 61bdcbf3028d
Revises: d7c79e0f87ef
Create Date: 2026-01-21 23:08:16.966953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61bdcbf3028d'
down_revision: Union[str, Sequence[str], None] = 'd7c79e0f87ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('distance_km', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('final_bill_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'final_bill_amount')
    op.drop_column('orders', 'distance_km')
    # ### end Alembic commands ###
