"""hardening_schema

Revision ID: b5b523aea61e
Revises: 5a11ef72a590
Create Date: 2026-01-20 15:48:20.679862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5b523aea61e'
down_revision: Union[str, Sequence[str], None] = '5a11ef72a590'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_role', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('metadata_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_events_id'), 'order_events', ['id'], unique=False)
    op.add_column('orders', sa.Column('pricing_breakdown', sa.JSON(), nullable=True))
    op.add_column('orders', sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('orders', sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('failed_delivery_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('rejection_reason', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('cancellation_reason', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('delivery_failure_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_failure_reason')
    op.drop_column('orders', 'cancellation_reason')
    op.drop_column('orders', 'rejection_reason')
    op.drop_column('orders', 'failed_delivery_at')
    op.drop_column('orders', 'cancelled_at')
    op.drop_column('orders', 'rejected_at')
    op.drop_column('orders', 'version')
    op.drop_column('orders', 'pricing_breakdown')
    op.drop_index(op.f('ix_order_events_id'), table_name='order_events')
    op.drop_table('order_events')
    # ### end Alembic commands ###
