"""workflow_compliance

Revision ID: d7c79e0f87ef
Revises: b5b523aea61e
Create Date: 2026-01-21 18:02:11.797994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7c79e0f87ef'
down_revision: Union[str, Sequence[str], None] = 'b5b523aea61e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Manually added Enum update
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'CONFIRMED'")
    
    op.add_column('orders', sa.Column('category', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('discrepancy_report', sa.JSON(), nullable=True))
    op.add_column('vendors', sa.Column('categories', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'categories')
    op.drop_column('orders', 'discrepancy_report')
    op.drop_column('orders', 'confirmed_at')
    op.drop_column('orders', 'category')
    # ### end Alembic commands ###
